### ISSUE TITLE
Incompatible xgroup command with Carmine 3.2

### ISSUE THREAD

**Issue by HassanYA** [oliyh/carmine-streams#12]
First off, thanks for an awesome library. I was dabbling with carmine-streams and found many useful features but could not use create-consumer-group! with Carmine 3.2. 

I was able to get this working with Carmine 3.1

deps.edn:
`{:paths ["src"]
 :deps {com.taoensso/carmine {:mvn/version "3.2.0"}
        carmine-streams/carmine-streams {:mvn/version "0.2.0-SNAPSHOT"}}}`

sandbox.clj:
`(ns enter-the-kitchen.sandbox
  (:require [taoensso.carmine :as car]
            [carmine-streams.core :as cs]))`
`(defonce pool  (car/connection-pool {}))`
`(def conn-opts {:pool pool
                :spec {:uri "redis://localhost:6379/"}})`
`(cs/create-consumer-group! conn-opts "mystream" "mygroup")`

Exception:
; Execution error (ArityException) at carmine-streams.core/create-consumer-group!$fn$fn$fn$fn$fn (core.clj:551).
; Wrong number of args (5) passed to: taoensso.carmine/xgroup

**Comment by oliyh** [comment]
I didn't have to change conn-opts to make it pass the tests, but they are pretty much default (i.e. leave them blank and carmine uses localhost:6379 automatically). They are passed through transparently anyway by this library so I'm not concerned about that.

**Comment by oliyh** [comment]
> Also, I do not want post another issue but is there a way to get the stream name and message id on the consumer callback?

Currently no. There is an implicit assumption that the values on the streams are key-value maps, so your callback receives Clojure maps. This means there are a few possibilities:

1. Add `:carmine-streams/message-id` to the map (may unintentionally propagate beyond your callback handler)
2. Add metadata to the map containing this information (avoids the above)
3. Change the callback function arity to include a context map containing this information (breaking api)

I am usually against using meta as it often doesn't survive when you do anything to the value (e.g. assoc on map) but it does feel like it genuinely is ephemeral metadata so it could be fitting in this case. What do you think?

**Comment by oliyh** [comment]
Will close this issue and move discussion to #14
