### ISSUE TITLE
Make message id, consumer name available to callback handler

### ISSUE THREAD

**Issue by oliyh** [oliyh/carmine-streams#14]
See #12

**Comment by HassanYA** [comment]
that was fast, thanks

**Comment by oliyh** [comment]
No problem. I'll do a snapshot release shortly. Out of interest are you already using the 0.2.0-SNAPSHOT or the 0.1.x release?

**Comment by oliyh** [comment]
Hi @HassanYA I have pushed a new `0.2.0-SNAPSHOT` to clojars, `carmine-streams-0.2.0-20230322.110505-2` to be specific with 3.2 compatibility and this change as well. Could you let me know if it works for you? If so I will do a release, thanks!

**Comment by HassanYA** [comment]
Yea man, it's perfect. Many thanks, I wish I could help in something. If you have anything you'd like me to work on in an open source clojure project, let me know <3

**Comment by oliyh** [comment]
Hello, that's a very generous offer! There are certainly things to do on a lot of my libraries, we can discuss further on Clojurians Slack if you like, I am `@oliy`, cheers
