### ISSUE TITLE
Clarify shutting down gracefully without thread interruption

### ISSUE THREAD

**Issue by S4G4R** [oliyh/carmine-streams#16]
Related : https://github.com/oliyh/carmine-streams/issues/4#issue-592538149

I want to shutdown my consumer after it has finished processing the message it currently is processing (and not read any further messages). But it isn't completely clear how to achieve this.

I'm using a future to start my consumer in another thread :
```clojure
(def consumer-future (future (cs/start-multi-consumer! ...)))
```

If I cancel the future during processing, and then unblock the consumer, the execution stops immediately with an exception (`java.util.concurrent.CancellationException`), which isn't the behavior I want 
```clojure
(future-cancel consumer-future)
(cs/unblock-consumers! conn consumer-name)
```

I tried something like
```clojure
(while (not (cs/unblocked? (deref consumer-future 100 ::timed-out)))
  (cs/unblock-consumers! conn consumer))
(future-cancel consumer-future)
```
But this does not stop the consumer from continuing to read messages until there are none left, even after the UNBLOCK message is sent. Looking through the [code](https://github.com/oliyh/carmine-streams/blob/master/src/carmine_streams/core.clj#L444), it seems like the only way to achieve this is via thread interruption (ie. throwing an exception).

The `default-control-fn`s docstring seems misleading unless I'm misunderstanding it, because it doesn't do what it's supposed to
```clojure
"Exits when unblocked via `unblock-consumers!` or any other error reading from redis."
```

I'd like to know if I'm missing something obvious or if this isn't supported at all at the moment.

**Comment by S4G4R** [comment]
I have been able to hack around this with a custom `control-fn`

```clojure
(defonce exit-consumer? (atom false))

(defn custom-control-fn
  "Like `carmine-streams.core/default-control-fn`, but supports exiting
  without thread interruption via the `exit-consumer?` atom containing
  a boolean value"
  [& [_ context :as args]]
  (cond
    @exit-consumer?
    (do (timbre/info context "Shutdown signal received")
        :exit)

    :else
    (apply cs/default-control-fn args)))
```

and then shutdown with
```clojure
(cs/unblock-consumers! conn consumer)
(reset! exit-consumer? true)
;; Set a timeout of 30seconds to shutdown
(with-timeout ... @consumer-future)
```

Although I'm not sure how clean this is

**Comment by oliyh** [comment]
Hi,

`(future-cancel consumer-future)` (which should interrupt the thread) combined with `(cs/unblock-consumers conn)` (which will send an `unblock` message through redis, to unblock consumer threads that are in the middle of a blocking read) should be sufficient.

Are you definitely providing the right consumer name when you call `(cs/unblock-consumers! conn consumer)`? What happens if you unblock everything using `(cs/unblock-consumers conn)`?

You could also try explicitly calling `(.interrupt consumer-future)` and you could also try using Thread, not future. Have a look at the following test: https://github.com/oliyh/carmine-streams/blob/master/test/carmine_streams/core_test.clj#L247-L250

Hope this helps!

**Comment by S4G4R** [comment]
Hi,

Thanks your help. I was able to find success with the following approach :

```clojure
(Thread. (fn [] (cs/start-multi-consumer! conn ...)))
(.start consumer-thread)

... Processing starts ...

(.interrupt consumer-thread)
(cs/unblock-consumers! conn consumer-name)
;; Block thread and wait until it is done, or force shutdown if 60secs pass
(diehard/with-timeout
  {:timeout-ms 60000
   :interrupt? true
   :on-success (fn [_] (timbre/warn "Consumer shutdown"))
   :on-failure (fn [_] (timbre/error (str "Timeout stopping consumer"
                                          " execution...")))}
  (.join consumer-thread))
```

but using `future` doesn't seem to work (throws `java.util.concurrent.CancellationException` and ends abruptly, I don't see the `... Thread interrupted`  log:
```clojure
(future (cs/start-multi-consumer! conn ...))

... Processing starts ...

(future-cancel consumer-future)
(cs/unblock-consumers! conn consumer-name)
;; Block thread and wait until it is done, or force shutdown if 60secs pass
(diehard/with-timeout
  {:timeout-ms 60000
   :interrupt? true
   :on-success (fn [_] (timbre/warn "Consumer shutdown"))
   :on-failure (fn [_] (timbre/error (str "Timeout stopping consumer"
                                          " execution...")))}
  @consumer-future)
```

Looking at the implementation of [`future-cancel`](https://github.com/clojure/clojure/blob/master/src/clj/clojure/core.clj#L7093), it appears that this is because it passes the argument [`mayInterruptIfRunning`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html#cancel-boolean-:~:text=boolean%C2%A0cancel(boolean-,mayInterruptIfRunning,-)) to [`.cancel`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html#cancel-boolean-) as true, which interrupts the task instead of letting it complete.

Changing from
```clojure
(future-cancel consumer-future)
```
to
```clojure
(.cancel consumer-future false)
```
would seem like it would work, but it didn't. There's probably something I'm missing here, but I'm happy to use `Thread` instead of `future`

**Comment by oliyh** [comment]
Hello,

Thanks for letting me know, it's useful information that futures don't work in quite the expected way. I've been burned by using futures a few times when I should have been using threads - futures will not log exceptions on the default exception handler, instead they will throw the exception only when you deref them, so they are best used for doing work which you intend to get later, and not suited to long running tasks that never return a value.

I will make a note of this in the readme to help future homers.
