### ISSUE TITLE
Carmine streams stop running after sometime

### ISSUE THREAD

**Issue by zerg000000** [oliyh/carmine-streams#17]
Carmine streams work fine for a period of time. 
However, it would be stopped by `UNBLOCKED client unblocked via CLIENT UNBLOCK` under read phase.

I am sure no client / or me to issue this CLIENT UNBLOCK command.

**Comment by oliyh** [comment]
Hi,

UNBLOCK shouldn't necessarily mean termination of the consumer.

When you do a read from a redis stream, if there are no messages there immediately you can ask it to block and wait for n milliseconds. While that thread is blocked, you can't do anything with it, so redis has this UNBLOCK message which will stop it blocking. Then, you have the opportunity to check if your consumer thread is interrupted or not and decide what to do.

Therefore, an UNBLOCK is not necessarily a bad thing, although I guess it is surprising if you don't think anything is sending it.

Are you seeing the consumers stop, or just unblock?

**Comment by zerg000000** [comment]
According to the `default-control-fn`, now the consumer will stop immediately. I just created my own version of `default-control-fn` which allow unblocked to be happened, but then the consumer could only be stopped by throwing exception.

https://github.com/oliyh/carmine-streams/blob/572de00fbf026eb262b2e6adf5a0f5661d1c1ca9/src/carmine_streams/core.clj#L78

**Comment by oliyh** [comment]
I think the control-fn could be enhanced to check for thread interruption when an unblock message is received, and exit if it is interrupted, and recur if not interrupted. This probably gives behaviour closer to the intention of an unblock message, which is simply to stop the blocking read in order to observe state and decide what to do. If I make this change will you be able to test a snapshot build?

Thanks

**Comment by zerg000000** [comment]
> I think the control-fn could be enhanced to check for thread interruption when an unblock message is received, and exit if it is interrupted, and recur if not interrupted. This probably gives behaviour closer to the intention of an unblock message, which is simply to stop the blocking read in order to observe state and decide what to do. If I make this change will you be able to test a snapshot build?
> 
> Thanks

I am okay to test it anytime. Thanks for your time.

**Comment by oliyh** [comment]
Hi @zerg000000 

Could you try `0.2.1-SNAPSHOT` from on clojars? The changes are here: https://github.com/oliyh/carmine-streams/compare/master...no-exit-on-unblock-only

Cheers

**Comment by zerg000000** [comment]
@oliyh 

After some testing, the consumer still stopped at `(and (unblocked? value) (.isInterrupted (Thread/currentThread)))`.

I will check what caused the interruption

**Comment by oliyh** [comment]
Hi @zerg000000 

It really sounds like you have something shutting down your consumers! Good luck finding it. I think this change still makes sense, though, so will merge it anyway. I'll wait a little longer to see if you have any luck confirming.

Cheers

**Comment by zerg000000** [comment]
@oliyh I can confirm it is working fine now, but it must be used with `Thread` because of the `.isInterrupted` and it is okay for my use case. Just curious how it combines with `virtual thread` and different types of thread pools.

I can close this issue, or just leave it for you to close it.

**Comment by oliyh** [comment]
This is now part of master and in version `0.2.2` on clojars

Thanks
