### ISSUE TITLE
SocketException is not properly handled

### ISSUE THREAD

**Issue by zerg000000** [oliyh/carmine-streams#18]
When SocketException is thrown, we will receive the following exception

```
java.lang.UnsupportedOperationException: nth not supported on this type: SocketException
```

Since we are trying to destruct Exception as a vector at this line

https://github.com/oliyh/carmine-streams/blob/572de00fbf026eb262b2e6adf5a0f5661d1c1ca9/src/carmine_streams/core.clj#L446

we could fix this by changing the return value in `(catch ...)`. e.g.

```clojure
(try
  ...
 (catch Exception ex
    [false ex])
```

**Comment by oliyh** [comment]
Hi,

Thanks for writing this up.

I wonder if this behaviour could or should also be changed in carmine, to make its API more consistent? But yes, I think carmine-streams should guard against this.

**Comment by zerg000000** [comment]
It should match the destructuring.

```clojure
(let [[_setname-ok? response]
      (try
        ... ;; should return [ v1 v2 ]
       (catch Exception e
         ... ;; should also return [ v1 v2 ]
        ))]
  ...
)
```

**Comment by oliyh** [comment]
Hi,

Please try version `0.2.2` on clojars

Thanks
